% Load training data
imdsTrain = imageDatastore('Grouped_Train', ...
    'IncludeSubfolders', true, ...
    'LabelSource', 'foldernames');

% Load test data
imdsTest = imageDatastore('Grouped_Test', ...
    'IncludeSubfolders', true, ...
    'LabelSource', 'foldernames');

% Resize images
inputSize = [227 227];
augTrain = augmentedImageDatastore(inputSize, imdsTrain);
augTest = augmentedImageDatastore(inputSize, imdsTest);


% Modify final layers for 3-class output
layers = net.Layers;
layers(end-2) = fullyConnectedLayer(3);
layers(end) = classificationLayer;

% Set training options
options = trainingOptions('sgdm', ...
    'InitialLearnRate', 1e-4, ...
    'MaxEpochs', 5, ...
    'MiniBatchSize', 64, ...
    'Shuffle', 'every-epoch', ...
    'Verbose', false, ...
    'Plots', 'training-progress');

% Train the model
trainedNet = trainNetwork(augTrain, layers, options);
