% Load training data
imdsTrain = imageDatastore('Grouped_Train', ...
    'IncludeSubfolders', true, ...
    'LabelSource', 'foldernames');

% Load test data
imdsTest = imageDatastore('Grouped_Test', ...
    'IncludeSubfolders', true, ...
    'LabelSource', 'foldernames');
